"""Update account table column

Revision ID: 32b1def31f34
Revises: 3c073acc11f0
Create Date: 2024-11-03 20:42:53.168197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32b1def31f34'
down_revision = '3c073acc11f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=50), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
