"""change created_by to agent_id

Revision ID: 4de275042333
Revises: 35ec65cdb40d
Create Date: 2024-11-11 17:59:43.617344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4de275042333'
down_revision = '35ec65cdb40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_car_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('used_car_listing_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_account', ['agent_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_car_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('used_car_listing_ibfk_2', 'user_account', ['created_by'], ['id'])
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
