"""view count

Revision ID: a4d357c66e65
Revises: 7bba30e01006
Create Date: 2024-11-11 16:58:16.403037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d357c66e65'
down_revision = '7bba30e01006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_car_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_account', ['seller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_car_listing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('view_count')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
